theme: jekyll-theme-minimal
title: My Portfolio
description: Portfolio of my projects and work
show_downloads: True
navigation:
  - title: Home
    url: https://www.linkedin.com/in/suryasathiyanarayanan/
  - title: Setup
    url: setup
